<?php

namespace Partymeister\Accounting\Http\Resources;

use Illuminate\Support\Str;
use Motor\Backend\Http\Resources\BaseResource;

/**
 * @OA\Schema(
 *   schema="AccountResource",
 *   @OA\Property(
 *     property="id",
 *     type="integer",
 *     example="1"
 *   ),
 *   @OA\Property(
 *     property="account_type",
 *     type="object",
 *     ref="#/components/schemas/AccountTypeResource"
 *   ),
 *   @OA\Property(
 *     property="name",
 *     type="string",
 *     example="My account"
 *   ),
 *   @OA\Property(
 *     property="has_pos",
 *     type="boolean",
 *     example="false"
 *   ),
 *   @OA\Property(
 *     property="currency_iso_4217",
 *     type="string",
 *     example="EUR"
 *   ),
 *   @OA\Property(
 *     property="pos_configuration",
 *     type="json",
 *     description="This is generated by the frontend part of the pos configurator"
 *   ),
 * )
 */
class AccountResource extends BaseResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id'                => (int) $this->id,
            'account_type'      => new AccountTypeResource($this->account_type),
            'account_type_id'   => (int) $this->account_type_id,
            'name'              => $this->name,
            'has_pos'           => (bool) $this->has_pos,
            'currency_iso_4217' => $this->currency_iso_4217,
            'pos_configuration' => $this->pos_configuration,
            'last_booking'      => Str::replaceFirst(' ', 'T', $this->last_booking),
            'balance'           => $this->balance,
        ];
    }
}
