<?php

namespace Partymeister\Accounting\Http\Requests\Backend;

use Motor\Admin\Http\Requests\Request;

/**
 * Class AccountRequest
 */
class AccountRequest extends Request
{
    /**
     * @OA\Schema(
     *   schema="AccountRequest",
     *   @OA\Property(
     *     property="account_type_id",
     *     type="integer",
     *     example="1"
     *   ),
     *   @OA\Property(
     *     property="name",
     *     type="string",
     *     example="My account"
     *   ),
     *   @OA\Property(
     *     property="has_pos",
     *     type="boolean",
     *     example="false"
     *   ),
     *   @OA\Property(
     *     property="currency_iso_4217",
     *     type="string",
     *     example="EUR"
     *   ),
     *   @OA\Property(
     *     property="pos_configuration",
     *     type="json",
     *     description="This is generated by the frontend part of the pos configurator"
     *   ),
     *   required={"account_type_id", "name", "currency_iso_4217"},
     * )
     */

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'account_type_id'   => 'required|integer',
            'name'              => 'required',
            'currency_iso_4217' => 'required',
            'has_pos'           => 'nullable|boolean',
            'pos_configuration' => 'nullable',
        ];
    }
}
